In [1]:
import numpy as np
import pandas as pd

In [4]:
sales_data = {
'Region':['North','South','East','West','North','South','East','West'],
'Salesperson':['A','B','C','D','E','F','G','H'],
'Sales':[12000,15000,13000,17000,16000,14000,15500,16500]
}

In [37]:
df_data = pd.DataFrame(sales_data)
print('--- Initial data Frame ----\n ')
print(df_data)

--- Initial data Frame ----

  Region Salesperson  Sales
0  North           A  12000
1  South           B  15000
2   East           C  13000
3   West           D  17000
4  North           E  16000
5  South           F  14000
6   East           G  15500
7   West           H  16500

In [10]:
# 1. Total Sales per region

print(" Sales per Region")
df_data.groupby('Region')['Sales'] .sum()

 Sales per Region

Region
East     28500
North    28000
South    29000
West     33500
Name: Sales, dtype: int64

In [36]:
#2. Top Sales Person
print(" Top Sales person:")
top_idx = df_data['Sales'].idxmax()
#print(top_idx)
print(df_data['Salesperson'][top_idx])

 Top Sales person:
D

In [30]:
# 3. Average Sales across Regions
print("Average sales across regions \n ")
df_data.groupby('Region')['Sales'].mean()

Average sales across regions

Region
East     14250.0
North    14000.0
South    14500.0
West     16750.0
Name: Sales, dtype: float64

In [31]:
# 4. Sort the data set by sales ascending
print(" Sales in Ascending order")
df_data.sort_values(by='Sales', ascending=True)

 Sales in Ascending order

  Region Salesperson  Sales
0  North           A  12000
2   East           C  13000
5  South           F  14000
1  South           B  15000
6   East           G  15500
4  North           E  16000
7   West           H  16500
3   West           D  17000