In [3]:
import numpy as np
import pandas as pd

In [4]:

data = {
'CustomerID':[101,102,103,104,105,106,107],
'Age':[25,45,35,50,23,40,60],
'PurchaseAmount':[250,600,400,800,150,700,900],
'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai','Delhi','Chennai']
}

In [5]:
df_data = pd.DataFrame(data)
df_data

   CustomerID  Age  PurchaseAmount     City
0         101   25             250    Delhi
1         102   45             600   Mumbai
2         103   35             400    Delhi
3         104   50             800  Chennai
4         105   23             150   Mumbai
5         106   40             700    Delhi
6         107   60             900  Chennai

In [7]:
# 1. Find the average purchase amount by city.
df_data.groupby('City')['PurchaseAmount'].mean()

City
Chennai    850.0
Delhi      450.0
Mumbai     375.0
Name: PurchaseAmount, dtype: float64

In [13]:
# 2. Identify customers with purchase above overall average.
df_average =df_data['PurchaseAmount'].mean()
print(" Average purchase : ", df_average)
df_highcustomer = df_data[df_data['PurchaseAmount']> df_average]
print("Customers are :\n ")
print(df_highcustomer)

 Average purchase :  542.8571428571429
Customers are :

   CustomerID  Age  PurchaseAmount     City
1         102   45             600   Mumbai
3         104   50             800  Chennai
5         106   40             700    Delhi
6         107   60             900  Chennai

In [33]:
#3 Find the city generating the highest revenue.
df_city = df_data.groupby('City')['PurchaseAmount'].sum()
print("Total purchase of each city:\n \n  ", df_city)
df_city_idx = df_city.idxmax()
print("\n")
print("Highest Revenue City is ", df_city_idx)
print("Purchase amount is ", df_city[df_city_idx])

Total purchase of each city:

   City
Chennai    1700
Delhi      1350
Mumbai      750
Name: PurchaseAmount, dtype: int64


Highest Revenue City is  Chennai
Purchase amount is  1700

In [48]:
# 4. Create a column Age_Group:

for i in range(len(df_data)):
  if (df_data['Age'][i]< 30):
    df_data.at[i,'Age Group'] ='young'
  elif (df_data['Age'][i] >= 30 and df_data['Age'][i] <= 50):
    df_data.at[i,'Age Group'] ='Adult'
  elif (df_data['Age'][i] > 30 and df_data['Age'][i] >50):
    df_data.at[i,'Age Group'] ='Senior'

df_data

   CustomerID  Age  PurchaseAmount     City Age Group
0         101   25             250    Delhi     young
1         102   45             600   Mumbai     Adult
2         103   35             400    Delhi     Adult
3         104   50             800  Chennai     Adult
4         105   23             150   Mumbai     young
5         106   40             700    Delhi     Adult
6         107   60             900  Chennai    Senior

In [50]:
#5. Find average purchase per age group.
df_data.groupby('Age Group')['PurchaseAmount'].mean()

Age Group
Adult     625.0
Senior    900.0
young     200.0
Name: PurchaseAmount, dtype: float64